(setq b (make-array 5))
(defun main ()
 (setq main_i 0)
 (princ b)
 (setf main_i 0)
 (loop while (< main_i 5) do  (setf (aref b main_i) main_i)
 (setf main_i (+ main_i 1))
)
 (princ b)
 (setf (aref b 0) 123)
 (princ (aref b 0))
 (princ b)
 (princ (aref b 10))
)
(main)
